/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_ISATTY 1

#define HAVE_STDBOOL_H 1

#define PACKAGE_NAME "HarfBuzz"

#define PACKAGE_VERSION "4.4.1"

